name: skydeploy
description: A sample command-line application.
version: 1.0.1
# homepage: https://www.example.com
environment:
  sdk: ">=2.10.0 <3.0.0"

dependencies:
  path: ^1.7.0
  skynet:
    git: https://github.com/redsolver/skynet
  prompts: ^1.3.1
  xdg_directories: ^0.1.2
  convert: ^2.1.1
  ansicolor: ^1.0.5
  http: ^0.12.2

dev_dependencies:
  pedantic: ^1.9.0
  test: ^1.14.4
